config/routes.rb
Rails.application.routes.draw do
  get '/chart', to: 'pages#chart', as: 'chart'
  post '/chart', to: 'pages#chart', as: 'chart_date'
  get '/days/:id/details', to: 'days#details', as: 'day_details'
  get '/create_day', to: 'days#create_day', as: 'day_create'
  get '/days/:id/alert_details', to: 'days#alert_details', as: 'day_alert_details'
  resources :user_preferences
  resources :crises
  resources :days, except: [:index] do
    resources :poohs
    resources :meals do
      resources :ingredients
      resources :meal_ingredients, only: [:new, :create, :destroy]
    end
  end
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pooh.rb
class Pooh < ApplicationRecord
  belongs_to :day
end

app/controllers/poohs_controller.rb
class PoohsController < ApplicationController
  def show
    @pooh = Pooh.find(params[:id])
  end

  def new
    @day = Day.find(params[:day_id])
    @pooh = Pooh.new
  end

  def create
    @pooh = Pooh.new(pooh_params)
    @pooh.day_id = params[:day_id]
    if @pooh.save
      check_if_crisis(Day.find(params[:day_id]))
      redirect_to day_path(params[:day_id])
    else
      render :new
    end
  end

  def edit
    @pooh = Pooh.find(params[:id])
    @day = Day.find(@pooh.day.id)
    check_if_crisis(Day.find(@day))
  end

  def update
    @pooh = Pooh.find(params[:id])
    @pooh.update(pooh_params)
    @day = Day.find(@pooh.day.id)
    redirect_to day_path(@day.id)
  end

  def destroy
    pooh = Pooh.find(params[:id])
    id = pooh.day.id
    pooh.destroy
    redirect_to day_path(id)
  end

  private

  def check_if_crisis(day)
    if day.pooh.where('blood = true').exists? && day.pain_rate > 6
      return if Crisis.where('start_date < ?', day.date).where('end_date > ?', day.date).exists?
      if Crisis.find_by_start_date(day.date + 1)
        crisis = Crisis.find_by_start_date(day.date + 1)
        crisis.start_date = day.date
        crisis.save
      elsif Crisis.find_by_end_date(day.date - 1)
        crisis = Crisis.find_by_end_date(day.date - 1)
        crisis.start_date = day.date
        crisis.save
      else
        Crisis.create(start_date: day.date, end_date: day.date)
      end
    end
  end

  def pooh_params
    params.require(:pooh).permit(:blood, :rate)
  end
end

app/views/poohs/delete.html.erb
<h1>Poohs#delete</h1>
<p>Find me in app/views/poohs/delete.html.erb</p>

app/views/poohs/edit.html.erb
<div class="container form-container">

  <div class="form-title">
    <h1>Editer ce pooh</h1>
  </div>

  <%= simple_form_for [ @day, @pooh ] do |f| %>
    <%= f.input :blood, label: "Sang" %>
    <%= f.input :rate, collection: 0..10, label: "Consistance", hint: "Notez la consistance de 0 (liquide) à 10 (solide)" %>
      <div class="form-buttons">
      <%= link_to "Annuler", :back, class: "btn btn-danger btn-annuler" %>
      <%= f.submit "Sauvegarder", class: "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/poohs/new.html.erb
<div class="container form-container">
  <div class="form-title">
    <% if @day.date == Date.today %>
      <h4>Ajouter un pooh pour aujourd'hui</h4>
    <% else %>
      <h4>Ajouter un pooh pour le <%= I18n.localize(@day.date, format: :long) %></h4>
    <% end %>
  </div>

  <%= simple_form_for [ @day, @pooh ] do |f| %>
  <%= f.input :rate, collection: 0..10, label: "Consistance", hint: "Notez la consistance de 0 (liquide) à 10 (solide)" %>
  <%= f.input :blood, label: "Sang" %>
  <div class="form-buttons">
    <%= link_to "Annuler", :back, class: "btn btn-danger btn-annuler" %>
    <%= f.submit "Ajouter un pooh à ma journée", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/poohs/show.html.erb
<div class="container">
  <div class="back-link">
    <%= link_to day_path(@pooh.day.id) do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
  </div>

  <div class="form-title">
    <h4>Pooh du <%= I18n.localize(@pooh.day.date, format: :long)  %></h4>
    <h6>Engeristré le <%= I18n.localize(@pooh.created_at, format: :long) %> à <%= I18n.localize(@pooh.created_at, format: :hours) %></h6>
  </div>
  <h4>Consistance: <%= @pooh.rate %>/10</h4>
  <h4>Sang: <%= @pooh.blood ? "Oui" : "Non" %></h4>

  <div class="form-buttons">
    <%= link_to "Supprimer", day_pooh_path(@pooh.day.id, @pooh.id), method: :delete, class:"btn btn-danger"  %>
    <%= link_to "Editer", edit_day_pooh_path(@pooh.day.id, @pooh.id), class:"btn btn-success" %>
  </div>
</div>