config/routes.rb
Rails.application.routes.draw do
  get '/chart', to: 'pages#chart', as: 'chart'
  post '/chart', to: 'pages#chart', as: 'chart_date'
  get '/days/:id/details', to: 'days#details', as: 'day_details'
  get '/create_day', to: 'days#create_day', as: 'day_create'
  get '/days/:id/alert_details', to: 'days#alert_details', as: 'day_alert_details'
  resources :user_preferences
  resources :crises
  resources :days, except: [:index] do
    resources :poohs
    resources :meals do
      resources :ingredients
      resources :meal_ingredients, only: [:new, :create, :destroy]
    end
  end
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<% if @alerts && @alerts.count > 0 %>
  <div class="slice-today-item item-total">
    <div class="slice-today-item-head">
      <i class="fa-solid fa-triangle-exclamation slice-logo"></i>
    </div>
    <h6>Quantités élevées sur les 3 derniers jours :</h6>
    <ul>
    <% @alerts.each do |alert| %>
      <li>
        <%= alert %>
      </li>
    <% end %>
    </ul>
    <div class="slice-today-item-bottom">
      <div class="graph-link">
        <%= link_to day_alert_details_path(@day.id) do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
    </div>
    </div>
<% end %>

app/views/shared/_calendar.html.erb
<div class="slice-today-item item-days">
  <div class="slice-today-item-head">
    <i class="fa-solid fa-calendar-day slice-logo"></i>
  </div>
  <%= month_calendar do |date| %>
    <% if date > Date.today %>
      <%= date.day %>
    <% else %>
      <% if Day.find_by_date(date) %>
        <% day = Day.find_by_date(date) %>
        <% link_to day_path(day.id) do %>
          <% if @day.date == date %>
            <div class="day-created day-today">
              <%= date.day %>
            </div>
          <% else %>
            <div class="day-created">
              <%= date.day %>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <% if @day.date == date %>
          <div class="day-not-created day-today" data-date=<%= date %> >
            <%= link_to date.day, new_day_path(date:date) %>
          </div>
        <% else %>
          <div class="day-not-created" data-date=<%= date %>>
            <%= link_to date.day, new_day_path(date:date) %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_day.html.erb
<div id="home-container">
  <div class="home-slice slice-today">
    <% if @day.date == Date.today %>
      <h4>Aujourd'hui</h4>
    <% else %>
      <h4>Journée du</h4>
    <% end %>
    <h3><%= I18n.localize(@day.date, format: :long) %></h3>
    <div class="slice-today-double-container">
      <%= render 'shared/state' %>
      <%= render 'shared/pooh' %>
    </div>
      <%= render 'shared/meal' %>
      <%= render 'shared/calendar' %>
  </div>
  <div class="home-slice slice-total">
    <%= render 'shared/total' %>
    <%= render 'shared/alert' %>
  </div>
  <div class="home-slice slice-graph">
    <%= render 'shared/graph' %>
  </div>
  <div class="home-slice slice-graph">
    <%= render 'crises/index' %>
  </div>
</div>

<div class="shadow">
  <div class="new_day_modal">
    <div class="container">
      <div class="form-title modal-title">
      </div>

      <div class="form-buttons">
        <%= link_to "Retour", :back, class: "btn btn-danger btn-annuler" %>
        <%= link_to "Créer cette journée", days_path(@day.date), method: :post, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_graph.html.erb
<div class="slice-today-item item-state">
  <div class="slice-today-item-head">
    <i class="fa-solid fa-chart-area slice-logo"></i>
    <%= link_to new_user_preference_path do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
  </div>
  <div class="chart">
    <% sorted_days = Day.all.sort_by { |day| day.date } %>
    <% @days =  sorted_days.select { |day| day.date >= (Date.today - 7) } %>
      <% data = [] %>

  <% data_hash_pooh = {} %>
  <% @days.map do |day|
    data_hash_pooh[day.date] = day.pooh.count
  end %>
  <% data << {name: 'Poohs', data: data_hash_pooh} %>

  <% data_hash_pain = {} %>
  <% @days.map do |day|
    if day.pain_rate.nil?
      data_hash_pain[day.date] = 0
    else
      data_hash_pain[day.date] = day.pain_rate
    end
  end %>
  <% data << {name: 'Douleur', data: data_hash_pain} %>

    <% @preferences = current_user.preferences %>
    <% @preferences.each do |preference|
      data_hash = {}
      @days.each do |day|
        ajr = @categories.select { |a| a[0] === preference.name }
        data_hash[day.date] = (day.send(preference.name.to_sym).fdiv(ajr.first[2])).ceil
      end
      data << {name: preference.name.capitalize, data: data_hash}
    end %>

    <%= line_chart data, download: {filename: "chart"} %>
  </div>
  <div class="slice-today-item-bottom">
    <div class="graph-link">
      <%= link_to chart_path do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_meal.html.erb
<div class="slice-today-item item-meal">
  <div class="slice-today-item-head">
    <i class="fa-solid fa-utensils slice-logo"></i>
    <%= link_to new_day_meal_path(@day.id) do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
    <% if @day.meals.count == 0 %>
      <h6>Aucune repas enregistré pour cette journée</h6>
    <% else %>
      <% @day.meals.each do |meal| %>
        <%= link_to meal.type, day_meal_path(@day.id, meal.id), class:"meal-type item-meal-link" %> :
          <br/>
        <% meal.ingredients.each do |ingredient| %>
            <% meal_ingredient = MealIngredient.where(meal_id: meal.id).find_by_ingredient_id(ingredient.id) %>
            <%= link_to ingredient.name, day_meal_ingredient_path(@day.id, meal.id, ingredient.id), class:"meal-ingredient item-meal-link" %> (<%= meal_ingredient.quantity.round %>g)
          <br/>
        <% end %>
      <% end %>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to :root, class: "navbar-brand" do %>
      <h2>MyMICI</h2>
    <% end %>

    <div class="nav-bar-items" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to destroy_user_session_path, class: "nav-link" do %>
              <i class="fa-solid fa-right-from-bracket"></i>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pooh.html.erb
<div class="slice-today-item item-state">
  <div class="slice-today-item-head">
    <i class="fa-solid fa-poo slice-logo"></i>
    <%= link_to new_day_pooh_path(@day.id) do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
    <% if @day.date.today? %>
      <h6><%= @day.pooh.count %> <%= 'pooh'.pluralize(@day.pooh.count + 1) %> aujourd'hui</h6>
    <% else %>
      <h6><%= @day.pooh.count %> <%= 'pooh'.pluralize(@day.pooh.count + 1) %> pour cette journée</h6>
    <% end %>
  <div class="slice-today-item-bottom">
    <div class="pooh-list">
      <% if @day.pooh %>
        <% @day.pooh.each do |pooh| %>
          <% if pooh.blood %>
            <%= link_to day_pooh_path(@day.id, pooh.id) do %>
            <div class="pooh-container pooh-blood-container">
              <h4 class="pooh-blood"><%= pooh.rate %><h4>
            </div>
            <% end %>
          <% else %>
            <%= link_to day_pooh_path(@day.id, pooh.id) do %>
            <div class="pooh-container pooh-no-blood-container">
              <h4 class="pooh-no-blood"><%= pooh.rate %><h4>
            </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_state.html.erb
<div class="slice-today-item item-state">
  <div class="slice-today-item-head">
    <i class="fa-solid fa-heart-pulse slice-logo"></i>
    <%= link_to edit_day_path(@day.id) do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
  </div>
    <% if @day.pain_rate.nil? && @day.comment.blank? %>
      <h6>Aucune information enregistrée</h6>
    <% else %>
      <% if @day.comment %>
        <h6><%= @day.comment %></h6>
      <% end %>
    <% end %>
  <div class="slice-today-item-bottom">
    <% if @day.pain_rate %>
      <h5>Douleur: <%= @day.pain_rate %>/10</h5>
    <% end %>
  </div>
</div>

app/views/shared/_total.html.erb
<div class="slice-today-item item-total">
  <div class="slice-today-item-head">
    <i class="fa-solid fa-align-justify slice-logo"></i>
    <%= link_to new_user_preference_path do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
  </div>
    <% current_user.preferences.each do |preference| %>
      <% total = @day.send(preference.name.to_sym) %>
      <% category = CATEGORIES.find {|c| c[0] == preference.name  } %>

      <% if @day.send(preference.name.to_sym) > category[2] %>
        <h6 class="total-alert"><%= preference.name.capitalize %> : <strong><%= @day.send(preference.name.to_sym) %> <%= preference.unity %><strong/></h6>
      <% else %>
        <h6><%= preference.name.capitalize %> : <strong><%= @day.send(preference.name.to_sym) %> <%= preference.unity %><strong/></h6>

      <% end %>

    <% end %>
  <div class="slice-today-item-bottom">
    <div class="graph-link">
      <%= link_to day_details_path(@day.id) do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    </div>
  </div>
</div>