config/routes.rb
Rails.application.routes.draw do
  get '/chart', to: 'pages#chart', as: 'chart'
  post '/chart', to: 'pages#chart', as: 'chart_date'
  get '/days/:id/details', to: 'days#details', as: 'day_details'
  get '/create_day', to: 'days#create_day', as: 'day_create'
  get '/days/:id/alert_details', to: 'days#alert_details', as: 'day_alert_details'
  resources :user_preferences
  resources :crises
  resources :days, except: [:index] do
    resources :poohs
    resources :meals do
      resources :ingredients
      resources :meal_ingredients, only: [:new, :create, :destroy]
    end
  end
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/chart.html.erb
<div class="container">
  <div class="chart-header">
    <%= link_to :back do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
    <%= link_to new_user_preference_path do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
  </div>
  <div class="chart">
    <% data = [] %>

    <% data_hash_pooh = {} %>
    <% @days.map do |day|
      data_hash_pooh[day.date] = day.pooh.count
    end %>
    <% data << {name: 'Poohs', data: data_hash_pooh} %>

    <% data_hash_pain = {} %>
    <% @days.map do |day|
      if day.pain_rate.nil?
        data_hash_pain[day.date] = 0
      else
        data_hash_pain[day.date] = day.pain_rate
      end
    end %>
    <% data << {name: 'Douleur', data: data_hash_pain} %>

    <% @preferences.each do |preference|
      data_hash = {}
      @days.each do |day|
        ajr = @categories.select { |a| a[0] === preference.name }
        data_hash[day.date] = (day.send(preference.name.to_sym).fdiv(ajr.first[2])).ceil
      end
      data << {name: preference.name.capitalize, data: data_hash}
    end %>
    <%= line_chart data, download: {filename: "chart"} %>
  </div>

  <div class="chart-date-search">
    <%= simple_form_for chart_date_path do |f| %>
      <%= f.input :start_date, as: :date,
                              order: [:day, :month, :year],
                              label: "Date de début" %>
      <%= f.input :end_date, as: :date,
                              order: [:day, :month, :year],
                              label: "Date de fin" %>
      <%= f.submit "Valider", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/day' %>