config/routes.rb
Rails.application.routes.draw do
  get '/chart', to: 'pages#chart', as: 'chart'
  post '/chart', to: 'pages#chart', as: 'chart_date'
  get '/days/:id/details', to: 'days#details', as: 'day_details'
  get '/create_day', to: 'days#create_day', as: 'day_create'
  get '/days/:id/alert_details', to: 'days#alert_details', as: 'day_alert_details'
  resources :user_preferences
  resources :crises
  resources :days, except: [:index] do
    resources :poohs
    resources :meals do
      resources :ingredients
      resources :meal_ingredients, only: [:new, :create, :destroy]
    end
  end
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :day
  has_one :meal_type
  has_many :meal_ingredients, dependent: :destroy
  has_many :ingredients, through: :meal_ingredients

  def type
    MealType.find(self.meal_type_id).name
  end
end

app/models/meal_type.rb
class MealType < ApplicationRecord
  has_many :meals
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
  end

  def show
    @meal = Meal.find(params[:id])
    @day = Day.find(params[:day_id])
    @meal_ingredient = MealIngredient.new
  end

  def new
    @day = Day.find(params[:day_id])
    @meal = Meal.new
  end

  def create
    @day = Day.find(params[:day_id])
    if @day.meals.where(meal_type_id: params[:meal][:meal_type_id]).count > 0
      @meal = @day.meals.where(meal_type_id: params[:meal][:meal_type_id]).first
      redirect_to day_meal_path(@meal.day.id, @meal.id)
    else
      @meal = Meal.new
      @meal.date = @day.date
      @meal.day_id = @day.id
      @meal.meal_type_id = params[:meal][:meal_type_id]
      if @meal.save
        redirect_to day_meal_path(@meal.day.id, @meal.id)
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    day = Day.find(params[:day_id])
    meal = Meal.find(params[:id])
    meal.destroy
    redirect_to day_path(day.id)
  end
end

app/views/meals/index.html.erb
<h1>Meals#index</h1>
<p>Find me in app/views/meals/index.html.erb</p>

app/views/meals/new.html.erb
<div class="container">
  <div class="form-title">
    <h1>Nouveau repas pour le <%= I18n.localize(@day.date, format: :long) %> </h1>
  </div>

  <%= simple_form_for [@day, @meal] do |f| %>
    <%= f.input :meal_type_id, collection: MealType.all, label: 'Type de repas' %>
      <div class="form-buttons">
        <%= link_to "Annuler", :back, class: "btn btn-danger btn-annuler" %>
        <%= f.submit "Ajouter", class: "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/meals/show.html.erb
<div class="container form-container">
  <div class="back-link">
    <%= link_to day_path(@day.id) do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
  </div>

  <div class="form-title">
    <h1><%= @meal.type %> du <%= I18n.localize(@meal.date, format: :long)  %></h1>
  </div>

  <div class="ingredient-list">
    <ul>
      <% @meal.ingredients.each do |ingredient| %>
        <li>
            <%= link_to ingredient.name, day_meal_ingredient_path(@day.id, @meal.id, ingredient.id) %>
            <% meal_ingredient = ingredient.meal_ingredients.find_by_meal_id(@meal.id) %>
            (<%= meal_ingredient.quantity.round %>g)
            <%= link_to day_meal_meal_ingredient_path(@day.id, @meal.id, ingredient.id), method: :delete do %>
              <i class="fa-solid fa-xmark"></i>
            <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="meal-show-buttons">
    <h2 class="btn btn-primary" id="add-meal-btn" >Ajouter un plat</h2>
    <%= link_to "Supprimer ce repas", day_meal_path(@meal.day.id, @meal.id), method: :delete, class: "btn btn-danger btn-annuler", data: {confirm: "Etes vous sûre de vouloir supprimer ce repas?"} %>
  </div>

  <div class="new-meal-ingredient-form">
    <%= simple_form_for [@day, @meal, @meal_ingredient] do |f| %>
      <%= f.input :ingredient_id, collection: Ingredient.all, label: 'Plat :', input_html: { class: 'select2' }, required: true  %>
      <%= f.input :quantity, label: 'Quantité (en gramme)', required: true %>
        <div class="form-buttons">
          <h2 class="btn btn-danger btn-annuler" id="btn-annuler">Annuler</h2>
          <%= f.submit "Ajouter", class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>